services:
  hugo:
    build: ./site
    command: hugo serve --bind 0.0.0.0 --baseURL https://alchemmist.xyz --port 1313
    container_name: hugo
    ports:
      - "1313:1313"
    restart: unless-stopped
    volumes:
      - ./site:/usr/src/app
    networks:
      - default
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - hugo
    restart: unless-stopped
    networks:
      - default
  umami-db:
    image: postgres:13
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: secret
    volumes:
      - ./umami-db:/var/lib/postgresql/data
    networks:
      - default
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    env_file:
      - ./umami.env
    ports: 
      - "3000:3000"
    depends_on: 
      - umami-db
    networks:
      - default
volumes:
  caddy_data:
  caddy_config:
networks:
  default:
    driver: bridge
