services:
  hugo-builder:
    build: ./site
    container_name: hugo-builder
    volumes:
      - static_site:/output
    networks:
      - default
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - static_site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - hugo-builder
    restart: unless-stopped
    networks:
      - default
  umami-db:
    image: postgres:15
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    environment:
      DATABASE_URL: postgres://umami:umami@umami-db:5432/umami
      APP_SECRET: your_super_secret_value 
    depends_on:
      - umami-db
    ports:
      - "3000:3000"
    networks:
      - default
    restart: unless-stopped
  cats:
    image: alchemmist/cats:latest
    container_name: cats
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - default
volumes:
  static_site:
  caddy_data:
  caddy_config:
  umami-db-data:
networks:
  default:
    driver: bridge
