services:
  hugo-builder:
    build: ./site
    container_name: hugo-builder
    volumes:
      - static_site:/output
    networks:
      - default
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - static_site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - hugo-builder
    restart: unless-stopped
    networks:
      - default
  umami-db:
    image: postgres:15
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    environment:
      DATABASE_URL: postgres://umami:umami@umami-db:5432/umami
      APP_SECRET: mossmossmoss
    depends_on:
      - umami-db
    ports:
      - "3000:3000"
    networks:
      - default
    restart: unless-stopped
  cats:
    image: alchemmist/cats:latest
    container_name: cats
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - default
  remark42:
    image: ghcr.io/umputun/remark42:latest
    container_name: remark42
    restart: always
    environment:
      - REMARK_URL=https://remark42.alchemmist.xyz/
      - SITE=alchemmist
      - SECRET=mossmossmoss
      - AUTH_ANON=true
      - AUTH_GITHUB_CID=mossmossmoss
      - AUTH_GITHUB_CSEC=mossmossmoss
    volumes:
      - ./data:/srv/var
      - ./remark42/custom.css:/srv/web/custom.css
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  static_site:
  caddy_data:
  caddy_config:
  umami-db-data:
networks:
  default:
    driver: bridge
