# The URL the site will be built for
base_url = "https://alchemical-blog.ru"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# theme = "terminimal"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "tags"}, 
    {name = "test"}, 
]

# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
feed_filenames = ["rss.xml", "atom.xml"]

# The theme supports feeds (RSS and ATOM)
generate_feeds = true


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "boron"

[extra]
# background_color = "dark"
# accent_color = "white"


# Put all your custom variables here

menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "blog", url = "$BASE_URL"},

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "about me", url = "$BASE_URL/about"},
    {name = "portfolio", url = "$BASE_URL/portfolio"},

    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/Alchemmist", newtab = true},
    {name = "telegram", url = "https://t.me/alchemmist", newtab = true},
]

logo_text = "alchemical blog"

# One of: blue, green, orange, pink, red.
# Defaults to blue.
# Append -light for light themes, e.g. blue-light
# Or append -auto, e.g. blue-auto
accent_color = "blue"

# One of: blue, dark, green, orange, pink, red, light, auto
# Enabling dark background will also modify primary font color to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "dark"

enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false

page_titles = "main_only"

# Optional: default image to use for OpenGraph.
#           If the page doesnt set og_image, use this one as fallback. Usefull
#           for indexes and taxonomies' pages.
#default_og_image = "static/ocean.jpg"

copyright_html = "My custom&nbsp;<b>copyright</b>"
