services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./content:/app/content  # Для обновления контента без пересборки
    restart: unless-stopped

