baseURL = 'https://alchemmist.xyz/'
languageCode = 'en-us'
title = 'alchemmist'

[build]
  writeStats = true

[minify]
  minifyOutput = true
  disableCSS = false
  disableJS = false
  disableHTML = false


disableKinds = ["taxonomy"]

[markup]
  [markup.highlight]
    style = "github"
    noClasses = false
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params]
  math = true

[taxonomies]
  tag = "tags"
  topic = "topics"
  genre = "genre"
  author = "author"
  status = "status"



defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
disableDefaultLanguageRedirect = false

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ru]
    languageName = "Русский"
    weight = 2

[outputs]
home = ["HTML", "RSS"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


