baseURL = 'https://alchemmist.xyz/'
languageCode = 'en-us'
title = 'alchemmist'

[markup]
  [markup.highlight]
    style = "github"
    noClasses = false
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
  math = true


[taxonomies]
  tag = "tags"
  topic = "topics"

