baseURL = 'https://alchemmist.xyz/'
languageCode = 'en-us'
title = 'alchemmist'

[markup]
  [markup.highlight]
    style = "github"
    noClasses = false
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params]
  math = true
  googleAnalytics = "G-11CS0ECH9L"

[taxonomies]
  tag = "tags"
  topic = "topics"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content"
  [languages.ru]
    languageName = "Русский"
    weight = 2
    contentDir = "content"
